### ISSUE TITLE
Option to use Sentry also outside of the plugin

### ISSUE THREAD

**Issue by jardakotesovec** [hydra-newmedia/hapi-sentry#16]
I was having some issues (exception not being sent in some cases) with Sentry, when I was using Sentry outside of hapi. I know that sentry is accessible via hapi server object, but there are cases when I want to init&use sentry even before hapi plugin is loaded so I can catch even exceptions when app is starting for example. 

Therefore I was using `const Sentry = require("@sentry/node");` which was loading different copy of Sentry, which made Sentry bit buggy. In any case loading two Sentry copies is asking for troubles.

So I was wondering if you would consider to make sentry as peerDependency, so it can be easily used also outside of the plugin. Alternatively what would work if there would be option to pass Sentry instance to plugin, so it would use the one I provide.

Hope it makes sense. Thanks! :-)

**Comment by guischdi** [comment]
Hi @jardakotesovec

I implemented the possibility to pass a Sentry instance (which was already initialized by calling `Sentry.init()`). The regarding Pull Request is linked above.

Note: if you pass in an `@sentry/node` instance of version `5.x.x` it will probably not work, because the implementation of the per request handler uses some functions which are seemingly not available on a version 5 instance (according to https://github.com/hydra-newmedia/hapi-sentry/issues/15#issuecomment-495707252).

**Comment by jardakotesovec** [comment]
@guischdi Excellent, thanks a lot. I think they already fixed issues with documentation for sentry 5. So thats hopefully also something for foreseeable future. But thats another ticket :-).
